# ===============================
# 1. Nodeでビルド
# ===============================
FROM node:22 AS build

WORKDIR /app

# package.jsonだけ先にコピー（キャッシュ効かせる）
COPY ./frontend/package*.json ./
RUN npm install
RUN npm install -D tailwindcss postcss autoprefixer

# ソースを全コピーしてビルド
COPY ./frontend ./
RUN npm run build


# ===============================
# 2. Nginxで静的配信
# ===============================
FROM nginx:latest AS production

# Nginx設定ファイルを上書き（後述）
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Nodeでビルドした静的ファイルをコピー
COPY --from=build /app/dist /usr/share/nginx/html

# ポート開放
EXPOSE 80

# nginx起動
CMD ["nginx", "-g", "daemon off;"]
